name: eslint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Install packages
        run: "npm install"
      - name: Run eslint
        run: "yarn eslint"
